# Generated by Django 4.1 on 2022-09-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'itilizate a', 'verbose_name_plural': 'itilizate_yo'},
        ),
    ]
