# Generated by Django 4.1 on 2022-09-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default=1, upload_to='./Pictures'),
            preserve_default=False,
        ),
    ]
