# Generated by Django 4.1 on 2022-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modpass',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
