# Generated by Django 4.1 on 2022-09-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imel',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modpass',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='non',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='siyati',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
