# Generated by Django 4.1 on 2022-09-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_imel_alter_user_modpass_alter_user_non_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='imel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modpass',
        ),
        migrations.RemoveField(
            model_name='user',
            name='non',
        ),
        migrations.RemoveField(
            model_name='user',
            name='siyati',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefon',
        ),
    ]
